void ldv_refcount_set(refcount_t *r, int n);
void ldv_refcount_inc(refcount_t *r);
void ldv_kref_init(struct kref *kref);
unsigned int ldv_kref_read(const struct kref *kref);
void ldv_put_device(struct device *dev);
void ldv_kobject_put(struct kobject *kobj);
struct device *ldv_get_device(struct device *dev);
struct kobject *ldv_kobject_get(struct kobject *kobj);
int ldv_kref_put(struct kref *kref, void (*release)(struct kref *kref));
void ldv_kref_get(struct kref *kref);
void ldv_kobject_init(struct kobject *kobj, struct kobj_type *ktype);
void ldv_kobject_init_internal(struct kobject *kobj);
struct usb_device *ldv_usb_get_dev(struct usb_device *dev);
void ldv_usb_put_dev(struct usb_device *dev);
int ldv_v4l2_device_register(struct device *dev, struct v4l2_device *v4l2_dev);
void ldv_v4l2_prio_init(struct v4l2_prio_state *global);
int ldv_v4l2_device_put(struct v4l2_device *v4l2_dev);
void ldv_v4l2_device_disconnect(struct v4l2_device *v4l2_dev);
void ldv_usb_set_intfdata(struct usb_interface *intf, void *data);
void ldv_refcount_dec(refcount_t *r);
unsigned int ldv_refcount_read(const refcount_t *r);
void ldv_video_device_release(struct video_device *vdev);
struct video_device *ldv_video_device_alloc(void);
void ldv_video_get(struct video_device *vdev);
void ldv_video_put(struct video_device *vdev);
void ldv_v4l2_device_release(struct kref *ref);
