#!/usr/bin/python3
import os
import json
import sys
import consulate

sys.path.append(os.path.join(os.path.dirname(__file__), os.path.pardir))

import utils as utils
import utils.bridge as bridge

expect_file = os.environ["CONTROLLER_NODE_CONFIG"]
with open(expect_file, encoding="ascii") as fh:
    conf = json.load(fh)

# Sign in
session = bridge.Session(conf["Klever Bridge"]["name"], conf["Klever Bridge"]["user"], conf["Klever Bridge"]["password"])

# Submit scheduler status
status = {
    "VerifierCloud": "DISCONNECTED",
    "Klever": "DISCONNECTED"
}

a = utils.get_output("ps -aux | grep -F \"klever-scheduler.py\" ")
ks_out = int(utils.get_output("ps -aux | grep -F \"native-scheduler\" -c"))
if ks_out > 2:
    status["Klever"] = "HEALTHY"
vc_out = int(utils.get_output("ps -aux | grep -F \"verifiercloud-scheduler\" -c"))
if vc_out > 2:
    status["VerifierCloud"] = "HEALTHY"

data = {
    "statuses": json.dumps(status)
}

session.json_exchange("service/set_schedulers_status/", data)

# Sign out
session.sign_out()

# Submit scheduler status to kv storage for debug
session = consulate.Consul()
try:
    session.kv["schedulers"] = json.dumps(status)
    exit(0)
except KeyError:
    print("Key-value storage is inaccessible.")
    exit(2)

__author__ = 'Ilja Zakharov <ilja.zakharov@ispras.ru>'
