#!/usr/bin/env bash
#
# Copyright (c) 2017 ISPRAS (http://www.ispras.ru)
# Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### BEGIN INIT INFO
# Provides:          klever-bridge
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Klever web-interface
# Description:       Klever Bridge is the web-inteface to other Klever components
### END INIT INFO

DESC="Klever Bridge"
NAME=klever-bridge
DAEMON=/usr/local/bin/gunicorn
PIDFILE=/var/run/"$NAME".pid
SCRIPTNAME=/etc/init.d/"$NAME"
DIR=/var/www/"$NAME"

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC"
        start_daemon -p ${PIDFILE} ${DAEMON} --daemon --pid ${PIDFILE} --chdir ${DIR} --timeout 900 \
            --workers $(( 2 * `cat /proc/cpuinfo | grep 'core id' | wc -l` + 1 )) --bind unix:${DIR}/gunicorn.sock \
            bridge.wsgi:application
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC"
        killproc -p ${PIDFILE} ${DAEMON}
        RETVAL=$?
        [ ${RETVAL} -eq 0 ] && [ -e ${PIDFILE} ] && rm -f ${PIDFILE}
        log_end_msg ${RETVAL}
        ;;
    restart)
        log_daemon_msg "Restarting $DESC"
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME} && exit 0 || exit $?
        ;;
    *)
        log_action_msg "Usage: $SCRIPTNAME {start|stop|status|restart}"
        exit 2
        ;;
esac

exit 0
