obj-m += mod_timer_pinned.o setup_deferrable_timer_on_stack.o del_timer_sync.o setup_timer_invoke.o mod_timer_pending.o init_timer.o setup_timer.o del_timer.o init_timer_invoke.o try_to_del_timer_sync.o setup_timer_on_stack.o init_timer_deferrable.o

