# Generated by Django 3.0.3 on 2020-12-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksafetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marks.UnsafeTag'),
        ),
        migrations.AlterField(
            model_name='safetagaccess',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.UnsafeTag'),
        ),
        migrations.DeleteModel(
            name='SafeTag',
        ),
    ]
