# Generated by Django 2.1.3 on 2019-07-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksafereport',
            name='associated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='markunknownreport',
            name='associated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='markunsafe',
            name='threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='markunsafehistory',
            name='threshold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='markunsafereport',
            name='associated',
            field=models.BooleanField(default=True),
        ),
    ]
