# Generated by Django 2.1.3 on 2018-12-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('jobs', '0002_auto_20181228_1202'),
        ('marks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafetagaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unsafetag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unsafetag',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marks.UnsafeTag'),
        ),
        migrations.AddField(
            model_name='unsafereporttag',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reports.ReportUnsafe'),
        ),
        migrations.AddField(
            model_name='unsafereporttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.UnsafeTag'),
        ),
        migrations.AddField(
            model_name='unsafeassociationlike',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnsafeReport'),
        ),
        migrations.AddField(
            model_name='unsafeassociationlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unknownassociationlike',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnknownReport'),
        ),
        migrations.AddField(
            model_name='unknownassociationlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetagaccess',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.SafeTag'),
        ),
        migrations.AddField(
            model_name='safetagaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetag',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetag',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marks.SafeTag'),
        ),
        migrations.AddField(
            model_name='safereporttag',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='reports.ReportSafe'),
        ),
        migrations.AddField(
            model_name='safereporttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.SafeTag'),
        ),
        migrations.AddField(
            model_name='safeassociationlike',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkSafeReport'),
        ),
        migrations.AddField(
            model_name='safeassociationlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportunsafetag',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsafe_tags', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='reportunsafetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marks.UnsafeTag'),
        ),
        migrations.AddField(
            model_name='reportsafetag',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_tags', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='reportsafetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marks.SafeTag'),
        ),
        migrations.AddField(
            model_name='markunsafetag',
            name='mark_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='marks.MarkUnsafeHistory'),
        ),
        migrations.AddField(
            model_name='markunsafetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marks.UnsafeTag'),
        ),
        migrations.AddField(
            model_name='markunsafereport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunsafereport',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markreport_set', to='marks.MarkUnsafe'),
        ),
        migrations.AddField(
            model_name='markunsafereport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markreport_set', to='reports.ReportUnsafe'),
        ),
        migrations.AddField(
            model_name='markunsafehistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunsafehistory',
            name='error_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.ConvertedTraces'),
        ),
        migrations.AddField(
            model_name='markunsafehistory',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnsafeCompare'),
        ),
        migrations.AddField(
            model_name='markunsafehistory',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marks.MarkUnsafe'),
        ),
        migrations.AddField(
            model_name='markunsafecompare',
            name='convert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnsafeConvert'),
        ),
        migrations.AddField(
            model_name='markunsafeattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Attr'),
        ),
        migrations.AddField(
            model_name='markunsafeattr',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='marks.MarkUnsafeHistory'),
        ),
        migrations.AddField(
            model_name='markunsafe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunsafe',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnsafeCompare'),
        ),
        migrations.AddField(
            model_name='markunsafe',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='markunknownreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunknownreport',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markreport_set', to='marks.MarkUnknown'),
        ),
        migrations.AddField(
            model_name='markunknownreport',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marks.UnknownProblem'),
        ),
        migrations.AddField(
            model_name='markunknownreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markreport_set', to='reports.ReportUnknown'),
        ),
        migrations.AddField(
            model_name='markunknownhistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunknownhistory',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marks.MarkUnknown'),
        ),
        migrations.AddField(
            model_name='markunknownattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Attr'),
        ),
        migrations.AddField(
            model_name='markunknownattr',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='marks.MarkUnknownHistory'),
        ),
        migrations.AddField(
            model_name='markunknown',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunknown',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Component'),
        ),
        migrations.AddField(
            model_name='markunknown',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='marksafetag',
            name='mark_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='marks.MarkSafeHistory'),
        ),
        migrations.AddField(
            model_name='marksafetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marks.SafeTag'),
        ),
        migrations.AddField(
            model_name='marksafereport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksafereport',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markreport_set', to='marks.MarkSafe'),
        ),
        migrations.AddField(
            model_name='marksafereport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markreport_set', to='reports.ReportSafe'),
        ),
        migrations.AddField(
            model_name='marksafehistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksafehistory',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marks.MarkSafe'),
        ),
        migrations.AddField(
            model_name='marksafeattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Attr'),
        ),
        migrations.AddField(
            model_name='marksafeattr',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='marks.MarkSafeHistory'),
        ),
        migrations.AddField(
            model_name='marksafe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marksafe',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='markassociationschanges',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errortraceconvertioncache',
            name='converted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.ConvertedTraces'),
        ),
        migrations.AddField(
            model_name='errortraceconvertioncache',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnsafeConvert'),
        ),
        migrations.AddField(
            model_name='errortraceconvertioncache',
            name='unsafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportUnsafe'),
        ),
        migrations.AlterIndexTogether(
            name='markunknown',
            index_together={('component', 'problem_pattern')},
        ),
    ]
