# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_unsupported_jobs'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markunsafehistory',
            name='error_trace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.File')
        ),
    ]
