# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markunsafereport',
            name='broken',
        ),
    ]
