# Generated by Django 2.1.3 on 2019-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_auto_20190321_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markunknownattr',
            old_name='mark',
            new_name='mark_version',
        ),
        migrations.RenameField(
            model_name='markunsafeattr',
            old_name='mark',
            new_name='mark_version',
        ),
        migrations.AlterField(
            model_name='marksafeattr',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='markunknownattr',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='markunsafeattr',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
