# Generated by Django 3.0.3 on 2020-12-07 11:55

import hashlib
from django.db import migrations, models


def add_fullnames_safe_tags(apps, schema_editor):
    SafeTag = apps.get_model("marks", "SafeTag")

    all_tags = {}
    for t in SafeTag.objects.all():
        all_tags[t.id] = {'name': t.name, 'parent': t.parent_id}

    for t in SafeTag.objects.all():
        ancestors_names = []
        p_id = t.id
        while p_id is not None:
            ancestors_names.append(all_tags[p_id]['name'])
            p_id = all_tags[p_id]['parent']
        t.name = " - ".join(reversed(ancestors_names))
        t.save()


def add_fullnames_unsafe_tags(apps, schema_editor):
    UnsafeTag = apps.get_model("marks", "UnsafeTag")

    all_tags = {}
    for t in UnsafeTag.objects.all():
        all_tags[t.id] = {'name': t.name, 'parent': t.parent_id}

    for t in UnsafeTag.objects.all():
        ancestors_names = []
        p_id = t.id
        while p_id is not None:
            ancestors_names.append(all_tags[p_id]['name'])
            p_id = all_tags[p_id]['parent']
        t.name = " - ".join(reversed(ancestors_names))
        t.save()


class Migration(migrations.Migration):
    dependencies = [('marks', '0002_auto_20201207_1455')]

    operations = [
        migrations.RunPython(add_fullnames_safe_tags),
        migrations.RunPython(add_fullnames_unsafe_tags),
    ]
