# Generated by Django 3.0.3 on 2020-12-16 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0002_auto_20201216_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnsafeTag',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='UnsafeTagAccess',
            new_name='TagAccess',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='mark_tag',
        ),
        migrations.AlterModelTable(
            name='tagaccess',
            table='mark_tag_access',
        ),
        migrations.DeleteModel(
            name='SafeTagAccess',
        ),
    ]
