# Generated by Django 2.0.4 on 2018-06-25 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('marks', '0002_auto_20180507_1631')]

    operations = [
        migrations.RemoveField(model_name='componentmarkunknownproblem', name='component'),
        migrations.RemoveField(model_name='componentmarkunknownproblem', name='problem'),
        migrations.RemoveField(model_name='componentmarkunknownproblem', name='report'),
        migrations.DeleteModel(name='ComponentMarkUnknownProblem')
    ]
