# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 12:58
from __future__ import unicode_literals

from django.db import migrations


def move_error_traces_to_history(apps, schema_editor):
    MarkUnsafe = apps.get_model('marks', 'MarkUnsafe')
    MarkUnsafeHistory = apps.get_model('marks', 'MarkUnsafeHistory')
    for mu in MarkUnsafe.objects.all():
        for muh in MarkUnsafeHistory.objects.filter(mark=mu):
            muh.error_trace = mu.error_trace
            muh.save()


def revert_move_error_traces_to_history(apps, schema_editor):
    MarkUnsafeHistory = apps.get_model('marks', 'MarkUnsafeHistory')
    for muh in MarkUnsafeHistory.objects.all():
        muh.mark.error_trace = muh.error_trace
        muh.mark.save()
        muh.error_trace = None
        muh.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_custom'),
        ('jobs', '0003_remove_unsupported_jobs'),
    ]

    operations = [
        migrations.RunPython(move_error_traces_to_history, revert_move_error_traces_to_history)
    ]
