# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_generate_defaults'),
        ('jobs', '0003_remove_unsupported_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markunsafe',
            name='error_trace',
        ),
        migrations.AlterField(
            model_name='markunsafehistory',
            name='error_trace',
            field=models.ForeignKey(default=0, null=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.File'),
            preserve_default=False,
        )
    ]
