# Generated by Django 2.0.7 on 2018-10-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20180625_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markunknown',
            name='problem_pattern',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unknownproblem',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
