# Generated by Django 2.1.7 on 2019-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20190711_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetag',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='safetag',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='safetag',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='unsafetag',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='unsafetag',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='unsafetag',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
