# Generated by Django 2.1.3 on 2019-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_auto_20190321_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksafe',
            old_name='type',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='markunknown',
            old_name='type',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='markunsafe',
            old_name='type',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='safetag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='unsafetag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
