# Generated by Django 2.1.3 on 2019-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_auto_20190322_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksafe',
            name='cache_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='markunknown',
            name='cache_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='markunsafe',
            name='cache_links',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
