# Generated by Django 2.1.3 on 2019-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto_20190327_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marksafeattr',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='markunsafeattr',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='markunknown',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='markunknownhistory',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
