# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto'),
    ]

    operations = [
        migrations.AddField(model_name='markunsafereport', name='manual', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='marksafereport', name='manual', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='markunknownreport', name='manual', field=models.BooleanField(default=False))
    ]
