# Generated by Django 2.1.3 on 2019-06-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_auto_20190425_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marksafe',
            options={'verbose_name': 'Safes mark'},
        ),
        migrations.AlterModelOptions(
            name='marksafehistory',
            options={'verbose_name': 'Safes mark version'},
        ),
        migrations.AlterModelOptions(
            name='markunknown',
            options={'verbose_name': 'Unknowns mark'},
        ),
        migrations.AlterModelOptions(
            name='markunknownhistory',
            options={'verbose_name': 'Unknowns mark version'},
        ),
        migrations.AlterModelOptions(
            name='markunsafe',
            options={'verbose_name': 'Unsafes mark'},
        ),
        migrations.AlterModelOptions(
            name='markunsafehistory',
            options={'verbose_name': 'Unsafes mark version'},
        ),
        migrations.RemoveField(
            model_name='marksafe',
            name='cache_links',
        ),
        migrations.RemoveField(
            model_name='markunknown',
            name='cache_links',
        ),
        migrations.RemoveField(
            model_name='markunsafe',
            name='cache_links',
        ),
    ]
