# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0007_set_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksafe',
            name='prime',
        ),
        migrations.RemoveField(
            model_name='markunknown',
            name='prime',
        ),
        migrations.RemoveField(
            model_name='markunsafe',
            name='prime',
        ),
        migrations.AddField(
            model_name='marksafereport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunknownreport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markunsafereport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
