# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('marks', '0011_set_type')]
    operations = [
        migrations.RemoveField(model_name='marksafereport', name='manual'),
        migrations.RemoveField(model_name='markunknownreport', name='manual'),
        migrations.RemoveField(model_name='markunsafereport', name='manual')
    ]
