# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0012_remove_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeAssociationLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkSafeReport')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mark_safe_association_like',
            },
        ),
        migrations.CreateModel(
            name='UnknownAssociationLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=False)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnknownReport')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mark_unknown_association_like',
            },
        ),
        migrations.AlterModelTable(
            name='unsafeassociationlike',
            table='mark_unsafe_association_like',
        ),
    ]
