# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0014_safetagaccess_unsafetagaccess'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='safetagaccess',
            table='marks_safe_tag_access',
        ),
        migrations.AlterModelTable(
            name='unsafetagaccess',
            table='marks_unsafe_tag_access',
        ),
    ]
