# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0018_set_convert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markunsafecompare',
            name='convert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.MarkUnsafeConvert'),
        ),
    ]
