# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0019_auto_20170919_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='markunknownhistory',
            name='is_regexp',
            field=models.BooleanField(default=True),
        ),
    ]
