# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0020_markunknownhistory_is_regexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='markunknown',
            name='is_regexp',
            field=models.BooleanField(default=True),
        ),
    ]
