# Generated by Django 2.1.3 on 2019-04-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodesconfiguration',
            old_name='cpu',
            new_name='cpu_model',
        ),
        migrations.RenameField(
            model_name='nodesconfiguration',
            old_name='cores',
            new_name='cpu_number',
        ),
        migrations.RenameField(
            model_name='nodesconfiguration',
            old_name='memory',
            new_name='disk_memory',
        ),
        migrations.RenameField(
            model_name='nodesconfiguration',
            old_name='ram',
            new_name='ram_memory',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='for_jobs',
            new_name='available_for_jobs',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='for_tasks',
            new_name='available_for_tasks',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='cores',
            new_name='reserved_cpu_number',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='memory',
            new_name='reserved_disk_memory',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='ram',
            new_name='reserved_ram_memory',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='jobs',
            new_name='running_verification_jobs',
        ),
        migrations.RenameField(
            model_name='workload',
            old_name='tasks',
            new_name='running_verification_tasks',
        ),
    ]
