# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvingprogress',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
