# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_solvingprogress_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvingprogress',
            name='estimated_total_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solvingprogress',
            name='global_average_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solvingprogress',
            name='local_average_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
