# Generated by Django 2.1.7 on 2019-08-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190628_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='file',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='file',
            new_name='archive',
        ),
    ]
