# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20170814_1614'),
        ('service', '0002_solvingprogress_fake'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sj', models.PositiveIntegerField(null=True)),
                ('failed_sj', models.PositiveIntegerField(null=True)),
                ('solved_sj', models.PositiveIntegerField(null=True)),
                ('expected_time_sj', models.PositiveIntegerField(null=True)),
                ('start_sj', models.DateTimeField(null=True)),
                ('finish_sj', models.DateTimeField(null=True)),
                ('total_ts', models.PositiveIntegerField(null=True)),
                ('failed_ts', models.PositiveIntegerField(null=True)),
                ('solved_ts', models.PositiveIntegerField(null=True)),
                ('expected_time_ts', models.PositiveIntegerField(null=True)),
                ('start_ts', models.DateTimeField(null=True)),
                ('finish_ts', models.DateTimeField(null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
    ]
