# Generated by Django 2.1.3 on 2019-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190426_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesconfiguration',
            name='disk_memory',
            field=models.PositiveIntegerField(verbose_name='Disk memory'),
        ),
        migrations.AlterField(
            model_name='nodesconfiguration',
            name='ram_memory',
            field=models.PositiveIntegerField(verbose_name='RAM memory'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='reserved_disk_memory',
            field=models.PositiveIntegerField(verbose_name='Reserved disk memory'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='reserved_ram_memory',
            field=models.PositiveIntegerField(verbose_name='Reserved RAM memory'),
        ),
    ]
