# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('service', '0003_jobprogress')]

    operations = [
        migrations.AddField(
            model_name='jobprogress', name='gag_text_sj', field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='jobprogress', name='gag_text_ts', field=models.CharField(max_length=128, null=True),
        ),
    ]
