# Generated by Django 2.1.3 on 2019-06-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190426_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='archive',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='archname',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='archive',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='archname',
            new_name='filename',
        ),
    ]
