obj-m += reg1.o reg2.o reg3.o order1.o unreg1.o unreg2.o unreg3.o
reg1-objs := reg1_file1.o
reg2-objs := reg2_file1.o
reg3-objs := reg3_file1.o
order1-objs := order1_file1.o
unreg1-objs := unreg1_file1.o
unreg2-objs := unreg2_file1.o
unreg3-objs := unreg3_file1.o
