# Generated by Django 2.1.3 on 2018-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('enter_time', models.DecimalField(decimal_places=4, max_digits=14)),
                ('execution_time', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('return_time', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('execution_delta', models.FloatField(default=0)),
                ('wait1', models.FloatField(default=0)),
                ('wait2', models.FloatField(default=0)),
                ('is_failed', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tools_call_logs',
            },
        ),
        migrations.CreateModel(
            name='LockTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lock_table',
            },
        ),
    ]
