# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(db_index=True, max_length=64)),
                ('file_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tools_files_to_check',
            },
        ),
    ]
