# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('enter_time', models.FloatField()),
                ('execution_time', models.FloatField()),
                ('return_time', models.FloatField()),
                ('execution_delta', models.FloatField()),
                ('wait1', models.FloatField()),
                ('wait2', models.FloatField()),
                ('is_failed', models.BooleanField()),
            ],
            options={
                'db_table': 'tools_call_logs',
            },
        ),
    ]
