# Generated by Django 2.0.4 on 2018-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('tools', '0002_auto_20180605_1656')]
    operations = [
        migrations.AlterField(model_name='calllogs', name='execution_time',
                              field=models.DecimalField(decimal_places=4, max_digits=14, null=True)),
        migrations.AlterField(model_name='calllogs', name='return_time',
                              field=models.DecimalField(decimal_places=4, max_digits=14, null=True)),
        migrations.AlterField(model_name='calllogs', name='wait1', field=models.FloatField(default=0)),
        migrations.AlterField(model_name='calllogs', name='wait2', field=models.FloatField(default=0)),
    ]
