# Generated by Django 2.1.7 on 2019-11-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='coverage_details',
            field=models.CharField(choices=[('0', 'Original C source files'), ('1', 'C source files including models'), ('2', 'All source files')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
