# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('jobs', '0001_initial')]
    operations = [migrations.RemoveField(model_name='job', name='type')]
