# Generated by Django 2.2.5 on 2020-02-10 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='decision',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
