# Generated by Django 2.2.5 on 2019-12-02 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(db_index=True)),
                ('check_date', models.DateTimeField(auto_now=True)),
                ('hash_sum', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'job_preset',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='preset_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
