# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='light',
            field=models.BooleanField(default=False),
        ),
    ]
