#
# Copyright (c) 2014-2016 ISPRAS (http://www.ispras.ru)
# Institute for System Programming of the Russian Academy of Sciences
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Generated by Django 1.9.5 on 2016-08-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models


def remove_unsupported_jobs(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')

    # Collect all jobs of classes unsupported any more. These jobs will be removed later.
    jobs_to_be_removed = []
    for job in Job.objects.all():
        if job.type not in ('0', '3'):
            jobs_to_be_removed.append(job)

    # Remove trees of unsupported jobs starting from leaves.
    while True:
        if not jobs_to_be_removed:
            break

        for job in jobs_to_be_removed:
            job_to_be_removed = job

            for job_possible_child in jobs_to_be_removed:
                if job_possible_child.parent == job_to_be_removed:
                    job_to_be_removed = None
                    break

            if job_to_be_removed:
                job.delete()
                jobs_to_be_removed.remove(job_to_be_removed)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_light'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('0', 'Verification of Linux kernel modules'), ('3', 'Validation on commits in Linux kernel Git repositories')], default='0', max_length=1),
        ),
        migrations.RunPython(remove_unsupported_jobs)
    ]
