# Generated by Django 2.1.3 on 2019-06-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190321_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runhistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_history', to='jobs.Job'),
        ),
    ]
