# Generated by Django 2.2.5 on 2020-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200210_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
