# Generated by Django 2.0.3 on 2018-04-27 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('jobs', '0002_remove_job_type')]

    operations = [
        migrations.RemoveField(model_name='jobhistory', name='parent'),
        migrations.AlterField(model_name='job', name='change_date', field=models.DateTimeField()),
        migrations.AlterField(
            model_name='jobhistory', name='change_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(model_name='jobhistory', name='change_date', field=models.DateTimeField(auto_now=True)),
    ]
