# Generated by Django 2.2.5 on 2019-12-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20191202_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('0', 'Not solved'), ('1', 'Pending'), ('2', 'Is solving'), ('3', 'Solved'), ('4', 'Failed'), ('5', 'Corrupted'), ('6', 'Cancelling'), ('7', 'Cancelled'), ('8', 'Terminated'), ('9', 'Uploading')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='status',
            field=models.CharField(choices=[('0', 'Not solved'), ('1', 'Pending'), ('2', 'Is solving'), ('3', 'Solved'), ('4', 'Failed'), ('5', 'Corrupted'), ('6', 'Cancelling'), ('7', 'Cancelled'), ('8', 'Terminated'), ('9', 'Uploading')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='UploadedJobArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='UploadedJobs')),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Extracting archive files'), ('2', 'Uploading files'), ('3', 'Uploading job with versions'), ('4', 'Uploading reports'), ('5', 'Associating marks and cache recalculation'), ('6', 'Finished'), ('7', 'Failed')], default='0', max_length=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateTimeField(null=True)),
                ('error', models.TextField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.Job')),
            ],
            options={
                'db_table': 'job_uploaded_archives',
            },
        ),
    ]
