# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('jobs', '0003_custom')]
    operations = [migrations.RemoveField(model_name='job', name='light')]
