# Generated by Django 2.0.7 on 2018-08-29 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('jobs', '0003_auto_20180427_1241')]
    operations = [migrations.RemoveField(model_name='job', name='safe_marks')]
