# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='safe_marks',
            field=models.BooleanField(default=False),
        ),
    ]
