# Generated by Django 2.2.5 on 2019-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_uploadedjobarchive_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfile',
            name='hash_sum',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
