# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('jobs', '0006_enable_safe_marks')]
    operations = [
        migrations.AlterField(
            model_name='job', name='weight',
            field=models.CharField(choices=[('0', 'Full-weight'), ('1', 'Lightweight')], default='0', max_length=1)
        ),
    ]
