# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('jobs', '0011_update_status')]

    operations = [migrations.RemoveField(model_name='jobhistory', name='name')]
