# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('jobs', '0013_unique_job_names')]

    operations = [
        migrations.AlterField(
            model_name='job', name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True)
        )
    ]
