# Generated by Django 2.1.3 on 2019-03-21 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportroot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomponentleaf',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='reportattr',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.AttrFile'),
        ),
        migrations.AddField(
            model_name='reportattr',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='coveragefile',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageArchive'),
        ),
        migrations.AddField(
            model_name='coveragedatastatistics',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageArchive'),
        ),
        migrations.AddField(
            model_name='coveragedata',
            name='covfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageFile'),
        ),
        migrations.AddField(
            model_name='coveragedata',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageDataValue'),
        ),
        migrations.AddField(
            model_name='comparisonobject',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CompareJobsInfo'),
        ),
        migrations.AddField(
            model_name='comparisonlink',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='reports.ComparisonObject'),
        ),
        migrations.AddField(
            model_name='comparisonlink',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='comparejobsinfo',
            name='root1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='comparejobsinfo',
            name='root2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='comparejobsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attrfile',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='additionalsources',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='reportcomponentleaf',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='reportcomponent',
            name='additional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.AdditionalSources'),
        ),
        migrations.AddField(
            model_name='reportcomponent',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computer'),
        ),
        migrations.AddField(
            model_name='reportcomponent',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.OriginalSources'),
        ),
        migrations.AddIndex(
            model_name='reportattr',
            index=models.Index(fields=['name', 'value'], name='report_attr_name_e431b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('root', 'identifier')},
        ),
        migrations.AlterIndexTogether(
            name='report',
            index_together={('root', 'identifier')},
        ),
        migrations.AddField(
            model_name='coveragearchive',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='componentresource',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_cache', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='componentinstances',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent'),
        ),
        migrations.AlterIndexTogether(
            name='comparisonobject',
            index_together={('info', 'verdict1', 'verdict2')},
        ),
    ]
