# Generated by Django 3.0.3 on 2021-05-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragearchive',
            name='has_extra',
        ),
        migrations.RemoveField(
            model_name='coveragestatistics',
            name='funcs_covered_extra',
        ),
        migrations.RemoveField(
            model_name='coveragestatistics',
            name='funcs_total_extra',
        ),
        migrations.RemoveField(
            model_name='coveragestatistics',
            name='lines_covered_extra',
        ),
        migrations.RemoveField(
            model_name='coveragestatistics',
            name='lines_total_extra',
        ),
    ]
