# Generated by Django 2.1.7 on 2019-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcomponent',
            old_name='verifier_input',
            new_name='verifier_files',
        ),
    ]
