# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_time', models.BigIntegerField()),
                ('wall_time', models.BigIntegerField()),
                ('memory', models.BigIntegerField()),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Component')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot')),
            ],
            options={
                'db_table': 'cache_report_light_resource',
            },
        ),
    ]
