# Generated by Django 2.1.3 on 2018-12-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportroot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportattr',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Attr'),
        ),
        migrations.AddField(
            model_name='reportattr',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.AttrFile'),
        ),
        migrations.AddField(
            model_name='reportattr',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='errortracesource',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='coveragefile',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageArchive'),
        ),
        migrations.AddField(
            model_name='coveragedatastatistics',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageArchive'),
        ),
        migrations.AddField(
            model_name='coveragedata',
            name='covfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageFile'),
        ),
        migrations.AddField(
            model_name='coveragedata',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageDataValue'),
        ),
        migrations.AddField(
            model_name='componentresource',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Component'),
        ),
        migrations.AddField(
            model_name='componentinstances',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Component'),
        ),
        migrations.AddField(
            model_name='comparejobsinfo',
            name='root1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='comparejobsinfo',
            name='root2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='comparejobsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comparejobscache',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CompareJobsInfo'),
        ),
        migrations.AddField(
            model_name='attrfile',
            name='root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
        migrations.AddField(
            model_name='attr',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.AttrName'),
        ),
        migrations.AddField(
            model_name='verdict',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='reportunsafe',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ErrorTraceSource'),
        ),
        migrations.AddField(
            model_name='reportunknown',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Component'),
        ),
        migrations.AddField(
            model_name='reportcomponentleaf',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='reportcomponentleaf',
            name='safe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='reports.ReportSafe'),
        ),
        migrations.AddField(
            model_name='reportcomponentleaf',
            name='unknown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='reports.ReportUnknown'),
        ),
        migrations.AddField(
            model_name='reportcomponentleaf',
            name='unsafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='reports.ReportUnsafe'),
        ),
        migrations.AddField(
            model_name='reportcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Component'),
        ),
        migrations.AddField(
            model_name='reportcomponent',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Computer'),
        ),
        migrations.AddField(
            model_name='coveragearchive',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='componentresource',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_cache', to='reports.ReportComponent'),
        ),
        migrations.AddField(
            model_name='componentinstances',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent'),
        ),
        migrations.AlterIndexTogether(
            name='comparejobscache',
            index_together={('info', 'verdict1', 'verdict2')},
        ),
        migrations.AlterIndexTogether(
            name='attr',
            index_together={('name', 'value')},
        ),
    ]
