# Generated by Django 2.1.3 on 2019-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190808_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
