# Generated by Django 3.0.3 on 2020-11-19 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0002_sourcecodecache'),
    ]

    operations = [
        migrations.RemoveField(model_name='reportunsafe', name='trace_id'),
    ]
