# Generated by Django 2.1.7 on 2019-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_coveragearchive_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalsources',
            old_name='archive',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='originalsources',
            old_name='archive',
            new_name='file',
        )
    ]
