# Generated by Django 2.2.5 on 2019-12-24 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20191115_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportroot',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='reportroot',
            name='resources',
        ),
        migrations.CreateModel(
            name='RootCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=20)),
                ('cpu_time', models.BigIntegerField(default=0)),
                ('wall_time', models.BigIntegerField(default=0)),
                ('memory', models.BigIntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('finished', models.IntegerField(default=0)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot')),
            ],
            options={
                'db_table': 'cache_report_root',
                'index_together': {('root', 'component')},
            },
        ),
    ]
