# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_lightresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportroot',
            name='safes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
