# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


def update_verifiers_time(apps, schema_editor):
    ReportComponent = apps.get_model("reports", "ReportComponent")
    for unsafe in apps.get_model("reports", "ReportUnsafe").objects\
            .exclude(parent__parent=None).exclude(parent__cpu_time=None):
        unsafe.verifier_time = ReportComponent.objects.get(id=unsafe.parent_id).cpu_time
        unsafe.save()
    for safe in apps.get_model("reports", "ReportSafe").objects\
            .exclude(parent__parent=None).exclude(parent__cpu_time=None):
        safe.verifier_time = ReportComponent.objects.get(id=safe.parent_id).cpu_time
        safe.save()


class Migration(migrations.Migration):
    dependencies = [('reports', '0002_auto')]
    operations = [migrations.RunPython(update_verifiers_time)]
