# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


def update_verifiers_time(apps, schema_editor):
    ReportComponent = apps.get_model("reports", "ReportComponent")
    for report in apps.get_model("reports", "ReportUnsafe").objects.select_related('parent'):
        if report.parent.parent is not None:
            cpu_time = ReportComponent.objects.get(id=report.parent_id).cpu_time
            if cpu_time is not None:
                report.verifier_time = ReportComponent.objects.get(id=report.parent_id).cpu_time
                report.save()
    for report in apps.get_model("reports", "ReportSafe").objects.select_related('parent'):
        if report.parent.parent is not None:
            cpu_time = ReportComponent.objects.get(id=report.parent_id).cpu_time
            if cpu_time is not None:
                report.verifier_time = ReportComponent.objects.get(id=report.parent_id).cpu_time
                report.save()


class Migration(migrations.Migration):
    dependencies = [('reports', '0002_auto')]
    operations = [migrations.RunPython(update_verifiers_time)]
