# Generated by Django 2.1.3 on 2019-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190321_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattr',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
