# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportroot_safes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsafe',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.File'),
        ),
        migrations.AlterField(
            model_name='reportsafe',
            name='proof',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
