# Generated by Django 2.1.3 on 2019-04-25 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190321_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentinstances',
            name='report',
        ),
        migrations.RemoveField(
            model_name='componentresource',
            name='report',
        ),
        migrations.AddField(
            model_name='reportroot',
            name='instances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reportroot',
            name='resources',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='ComponentInstances',
        ),
        migrations.DeleteModel(
            name='ComponentResource',
        ),
    ]
