# Generated by Django 2.2.5 on 2019-12-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20191224_1854'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='rootcache',
            index_together={('component', 'root')},
        ),
    ]
