# Generated by Django 2.1.3 on 2019-09-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_coveragedatastatistics_coveragestatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsafe',
            name='proof',
        ),
    ]
