# Generated by Django 2.1.3 on 2019-06-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190425_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalsources',
            name='archive',
            field=models.FileField(upload_to='OriginalSources'),
        ),
        migrations.AlterField(
            model_name='reportroot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roots', to=settings.AUTH_USER_MODEL),
        ),
    ]
