# Generated by Django 2.0.4 on 2018-06-25 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('reports', '0004_alter_fields')]

    operations = [
        migrations.RemoveField(model_name='componentunknown', name='component'),
        migrations.RemoveField(model_name='componentunknown', name='report'),
        migrations.DeleteModel(name='ComponentUnknown')
    ]
