# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160727_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttrStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safes', models.PositiveIntegerField(default=0)),
                ('unsafes', models.PositiveIntegerField(default=0)),
                ('unknowns', models.PositiveIntegerField(default=0)),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Attr')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.AttrName')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent')),
            ],
            options={
                'db_table': 'cache_report_attr_statistic',
            },
        ),
    ]
