# Generated by Django 2.1.7 on 2020-01-17 07:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20191226_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomponent',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
    ]
