# Generated by Django 2.1.3 on 2019-09-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_reportsafe_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragearchive',
            name='name',
            field=models.CharField(default='-', max_length=128),
        ),
    ]
