# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_attrstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_total', models.PositiveIntegerField(default=0)),
                ('bt_num', models.PositiveIntegerField(default=0)),
                ('avtg_total', models.PositiveIntegerField(default=0)),
                ('avtg_fail', models.PositiveIntegerField(default=0)),
                ('vtg_fail', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'report_tasks_numbers',
            },
        ),
        migrations.CreateModel(
            name='TaskStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tasks', models.BigIntegerField(default=0)),
                ('average_time', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'cache_report_task_statistic',
            },
        ),
        migrations.AddField(
            model_name='reportroot',
            name='average_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportroot',
            name='tasks_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportroot',
            name='tasks_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasksnumbers',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportRoot'),
        ),
    ]
