# Generated by Django 2.1.3 on 2019-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_coveragearchive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragearchive',
            name='has_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coveragestatistics',
            name='funcs_covered_extra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coveragestatistics',
            name='funcs_total_extra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coveragestatistics',
            name='lines_covered_extra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coveragestatistics',
            name='lines_total_extra',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
