# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_confirmed_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Component')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent')),
            ],
        ),
    ]
