# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_componentinstances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparejobsinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
