# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_reportcomponent_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomponent',
            name='coverage_arch',
            field=models.FileField(null=True, upload_to=reports.models.get_component_path),
        ),
    ]
