# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('reports', '0014_auto_20170830_1023')]

    operations = [
        migrations.RemoveField(model_name='reportcomponent', name='coverage'),
        migrations.RemoveField(model_name='reportcomponent', name='log'),
        migrations.RemoveField(model_name='reportsafe', name='proof'),
        migrations.RemoveField(model_name='reportunknown', name='problem_description'),
        migrations.RemoveField(model_name='reportunsafe', name='error_trace')
    ]
