# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_move_verifiers_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cache_report_coverage_data',
            },
        ),
        migrations.CreateModel(
            name='CoverageDataStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('data', models.FileField(upload_to='CoverageData')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent')),
            ],
            options={
                'db_table': 'cache_report_coverage_data_stat',
            },
        ),
        migrations.CreateModel(
            name='CoverageDataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashsum', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=128)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'cache_report_coverage_data_values',
            },
        ),
        migrations.CreateModel(
            name='CoverageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('file', models.FileField(null=True, upload_to=reports.models.get_coverage_dir)),
                ('covered_lines', models.PositiveIntegerField(default=0)),
                ('covered_funcs', models.PositiveIntegerField(default=0)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('total_funcs', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent')),
            ],
            options={
                'db_table': 'cache_report_coverage_file',
            },
        ),
        migrations.AlterModelTable(
            name='componentinstances',
            table='cache_report_component_instances',
        ),
        migrations.AddField(
            model_name='coveragedata',
            name='covfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageFile'),
        ),
        migrations.AddField(
            model_name='coveragedata',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageDataValue'),
        ),
    ]
