# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20170925_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=128)),
                ('archive', models.FileField(null=True, upload_to=reports.models.get_coverage_arch_dir)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportComponent')),
            ],
            options={
                'db_table': 'report_coverage_archive',
            },
        ),
    ]
