# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('reports', '0022_move_coverages')]

    operations = [
        migrations.RemoveField(model_name='coveragedatastatistics', name='report'),
        migrations.RemoveField(model_name='coveragefile', name='report'),
        migrations.RemoveField(model_name='reportcomponent', name='coverage'),
        migrations.AddField(
            model_name='coveragedatastatistics', name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageArchive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coveragefile', name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.CoverageArchive'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coveragearchive', name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='reports.ReportComponent'),
        ),
    ]
