# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20171009_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomponent',
            name='covnum',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
