# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('reports', '0025_count_covnum')]

    operations = [
        migrations.AlterField(model_name='comparejobscache', name='reports1', field=models.TextField()),
        migrations.AlterField(model_name='comparejobscache', name='reports2', field=models.TextField()),
        migrations.AlterField(
            model_name='comparejobscache', name='verdict1',
            field=models.CharField(choices=[('0', 'Total safe'), ('1', 'Found all unsafes'), ('2', 'Found not all unsafes'), ('3', 'Unknown'), ('4', 'Unmatched'), ('5', 'Broken')], max_length=1),
        ),
        migrations.AlterField(
            model_name='comparejobscache', name='verdict2',
            field=models.CharField(choices=[('0', 'Total safe'), ('1', 'Found all unsafes'), ('2', 'Found not all unsafes'), ('3', 'Unknown'), ('4', 'Unmatched'), ('5', 'Broken')], max_length=1),
        ),
    ]
