# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_auto_20171026_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsafe',
            old_name='verifier_time',
            new_name='cpu_time',
        ),
        migrations.RenameField(
            model_name='reportunsafe',
            old_name='verifier_time',
            new_name='cpu_time',
        ),
    ]
