# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20171027_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsafe',
            name='memory',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsafe',
            name='wall_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportunknown',
            name='cpu_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reportunknown',
            name='memory',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reportunknown',
            name='wall_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reportunsafe',
            name='memory',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportunsafe',
            name='wall_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
