obj-m += safe.o rcu-more-unlocks.o rcu-lock-at-read.o rcu-lock-at-exit.o
obj-m += rcu-bh-more-unlocks.o rcu-bh-lock-at-read.o rcu-bh-lock-at-exit.o
obj-m += rcu-sched-more-unlocks.o rcu-sched-lock-at-read.o rcu-sched-lock-at-exit.o
obj-m += srcu-more-unlocks.o srcu-lock-at-read.o srcu-lock-at-exit.o