obj-m += default_array_invoke.o default_callbacks.o default_deregister.o default_invoke.o default_register.o external_invoke.o external_type_invoke.o no_exit.o double_invoke.o
external_invoke-objs := external_invoke1.o external_invoke2.o
external_type_invoke-objs := external_type_invoke1.o external_type_invoke2.o
