# Generated by Django 2.1.3 on 2019-03-21 12:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSafeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('marks_total', models.PositiveIntegerField(default=0)),
                ('marks_confirmed', models.PositiveIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('0', 'Unknown'), ('1', 'Incorrect proof'), ('2', 'Missed target bug'), ('3', 'Incompatible marks'), ('4', 'Without marks')], default='4', max_length=1)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cache_safe',
            },
        ),
        migrations.CreateModel(
            name='ReportUnknownCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('marks_total', models.PositiveIntegerField(default=0)),
                ('marks_confirmed', models.PositiveIntegerField(default=0)),
                ('problems', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cache_unknown',
            },
        ),
        migrations.CreateModel(
            name='ReportUnsafeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('marks_total', models.PositiveIntegerField(default=0)),
                ('marks_confirmed', models.PositiveIntegerField(default=0)),
                ('total_similarity', models.FloatField(default=0)),
                ('verdict', models.CharField(choices=[('0', 'Unknown'), ('1', 'Bug'), ('2', 'Target bug'), ('3', 'False positive'), ('4', 'Incompatible marks'), ('5', 'Without marks')], default='5', max_length=1)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cache_unsafe',
            },
        ),
        migrations.CreateModel(
            name='SafeMarkAssociationChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('kind', models.CharField(choices=[('0', 'Changed'), ('1', 'New'), ('2', 'Deleted')], max_length=1)),
                ('verdict_old', models.CharField(choices=[('0', 'Unknown'), ('1', 'Incorrect proof'), ('2', 'Missed target bug'), ('3', 'Incompatible marks'), ('4', 'Without marks')], max_length=1)),
                ('verdict_new', models.CharField(choices=[('0', 'Unknown'), ('1', 'Incorrect proof'), ('2', 'Missed target bug'), ('3', 'Incompatible marks'), ('4', 'Without marks')], max_length=1)),
                ('tags_old', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tags_new', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'cache_safe_mark_associations_changes',
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTableWithRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnknownMarkAssociationChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('kind', models.CharField(choices=[('0', 'Changed'), ('1', 'New'), ('2', 'Deleted')], max_length=1)),
                ('problems_old', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('problems_new', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cache_unknown_mark_associations_changes',
            },
        ),
        migrations.CreateModel(
            name='UnsafeMarkAssociationChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('kind', models.CharField(choices=[('0', 'Changed'), ('1', 'New'), ('2', 'Deleted')], max_length=1)),
                ('verdict_old', models.CharField(choices=[('0', 'Unknown'), ('1', 'Bug'), ('2', 'Target bug'), ('3', 'False positive'), ('4', 'Incompatible marks'), ('5', 'Without marks')], max_length=1)),
                ('verdict_new', models.CharField(choices=[('0', 'Unknown'), ('1', 'Bug'), ('2', 'Target bug'), ('3', 'False positive'), ('4', 'Incompatible marks'), ('5', 'Without marks')], max_length=1)),
                ('tags_old', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tags_new', django.contrib.postgres.fields.jsonb.JSONField()),
                ('total_similarity_old', models.FloatField()),
                ('total_similarity_new', models.FloatField()),
            ],
            options={
                'db_table': 'cache_unsafe_mark_associations_changes',
            },
        ),
    ]
