# Generated by Django 3.0.3 on 2020-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportsafecache',
            old_name='marks_total',
            new_name='marks_automatic',
        ),
        migrations.RenameField(
            model_name='reportunknowncache',
            old_name='marks_total',
            new_name='marks_automatic',
        ),
        migrations.RenameField(
            model_name='reportunsafecache',
            old_name='marks_total',
            new_name='marks_automatic',
        ),
        migrations.AddField(
            model_name='reportunsafecache',
            name='status',
            field=models.CharField(choices=[('0', 'Unreported'), ('1', 'Reported'), ('2', 'Fixed'), ('3', 'Rejected'), ('4', 'Incompatible marks'), ('5', 'Without bugs')], max_length=1, null=True),
        ),
    ]
