# Generated by Django 3.0.3 on 2020-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0002_auto_20200820_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsafecache',
            name='marks_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportunknowncache',
            name='marks_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportunsafecache',
            name='marks_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
