# Generated by Django 3.0.3 on 2020-08-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0003_auto_20200820_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsafemarkassociationchanges',
            name='status_new',
            field=models.CharField(choices=[('0', 'Unreported'), ('1', 'Reported'), ('2', 'Fixed'), ('3', 'Rejected'), ('4', 'Incompatible marks')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='unsafemarkassociationchanges',
            name='status_old',
            field=models.CharField(choices=[('0', 'Unreported'), ('1', 'Reported'), ('2', 'Fixed'), ('3', 'Rejected'), ('4', 'Incompatible marks')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reportunsafecache',
            name='status',
            field=models.CharField(choices=[('0', 'Unreported'), ('1', 'Reported'), ('2', 'Fixed'), ('3', 'Rejected'), ('4', 'Incompatible marks')], max_length=1, null=True),
        ),
    ]
