# Generated by Django 2.0.4 on 2018-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.AlterField(model_name='view', name='type', field=models.CharField(choices=[
            ('0', 'component attributes'), ('1', 'jobTree'), ('2', 'DecisionResults'),
            ('3', 'reportChildren'), ('4', 'SafesAndUnsafesList'), ('5', 'SafesAndUnsafesList'),
            ('6', 'UnknownsList'), ('7', 'marksList'), ('8', 'marksList'), ('9', 'marksList'),
            ('10', 'UnsafeAssMarks'), ('11', 'SafeAssMarks'), ('12', 'UnknownAssMarks'),
            ('13', 'UnsafeAssReports'), ('14', 'SafeAndUnknownAssReports'), ('15', 'SafeAndUnknownAssReports'),
            ('16', 'AssociationChanges'), ('17', 'AssociationChanges'), ('18', 'AssociationChanges')
        ], default='1', max_length=2)),
    ]
