# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='triangles',
            field=models.BooleanField(default=False),
        ),
    ]
