# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended',
            name='triangles',
            field=models.BooleanField(default=True),
        ),
    ]
