# Generated by Django 2.1.3 on 2019-06-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataview',
            name='type',
            field=models.CharField(choices=[('0', 'component attributes'), ('1', 'jobTree'), ('2', 'DecisionResults'), ('3', 'reportChildren'), ('4', 'SafesAndUnsafesList'), ('5', 'SafesAndUnsafesList'), ('6', 'UnknownsList'), ('7', 'marksList'), ('8', 'marksList'), ('9', 'marksList'), ('10', 'UnsafeAssMarks'), ('11', 'SafeAssMarks'), ('12', 'UnknownAssMarks'), ('13', 'UnsafeAssReports'), ('14', 'SafeAndUnknownAssReports'), ('15', 'SafeAndUnknownAssReports'), ('16', 'AssociationChanges'), ('17', 'AssociationChanges'), ('18', 'AssociationChanges')], max_length=2),
        ),
    ]
