# Generated by Django 3.0.3 on 2020-11-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='declarations_number',
            field=models.PositiveIntegerField(default=3, help_text='Error trace declarations number threshold that should be opened by default', verbose_name='Number of declarations in error trace'),
        ),
    ]
