# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
