# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_view_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='type',
            field=models.CharField(choices=[
                ('0', 'component attributes'),
                ('1', 'job tree'),
                ('2', 'job view'),
                ('3', 'component children list'),
                ('4', 'unsafes list'),
                ('5', 'safes list'),
                ('6', 'unknowns list'),
                ('7', 'unsafe marks'),
                ('8', 'safe marks'),
                ('9', 'unknown marks'),
                ('10', 'unsafe associated marks'),
                ('11', 'safe associated marks'),
                ('12', 'unknown associated marks'),
                ('13', 'unsafe mark associated reports'),
                ('14', 'safe mark associated reports'),
                ('15', 'unknown mark associated reports'),
                ('16', 'safe association changes'),
                ('17', 'unsafe association changes'),
                ('18', 'unknown association changes')
            ], default='1', max_length=2),
        ),
    ]
