# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended',
            name='coverage_weight',
            field=models.CharField(choices=[('0', 'With data'), ('1', 'Without data')], default='0', max_length=1),
        ),
    ]
