# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_extended_coverage_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extended',
            name='coverage_weight',
        ),
        migrations.AddField(
            model_name='extended',
            name='coverage_data',
            field=models.BooleanField(default=True),
        ),
    ]
