# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_update_marks_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='type',
            field=models.CharField(choices=[('0', 'component attributes'), ('1', 'job tree'), ('2', 'job view'), ('3', 'component children list'), ('4', 'unsafes list'), ('5', 'safes list'), ('6', 'unknowns list'), ('7', 'unsafe marks'), ('8', 'safe marks'), ('9', 'unknown marks'), ('10', 'unsafe associated marks'), ('11', 'safe associated marks'), ('12', 'unknown associated marks')], default='1', max_length=2),
        ),
    ]
