# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170814_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='coverage_data',
            field=models.BooleanField(default=False),
        ),
    ]
